/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutmeComponent: typeof import('./src/components/aboutmeComponent.vue')['default']
    BackgroundComponent: typeof import('./src/components/backgroundComponent.vue')['default']
    BCarousel: typeof import('bootstrap-vue-next')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next')['BCarouselSlide']
    HeadComponent: typeof import('./src/components/headComponent.vue')['default']
    MeComponent: typeof import('./src/components/meComponent.vue')['default']
    ProjectsComponent: typeof import('./src/components/projectsComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsComponent: typeof import('./src/components/skillsComponent.vue')['default']
    StarComponent: typeof import('./src/components/starComponent.vue')['default']
    TestComp: typeof import('./src/components/testComp.vue')['default']
  }
}
